dev:
  app_function: run.app
  aws_region: us-east-1
  profile_name: default
  project_name: sts
  runtime: python3.7
  s3_bucket: sts-backend
  exclude:
  - .git
  - .gitignore
  - .gitsubmodules
  - .graphqlconfig.yaml
  - .pytest_cache
  - .python-version
  - .pytest_cache
  - local
  - tests
  - scripts
  - venv
  - orka_api.egg-info
  - pip-wheel-metadata
  - README.md
  - schema.graphql
  - tasks.py
  - orka_api/db.db
  - Orka-API-Context-for-Insomnia.yaml
  - untitled.sublime-project
  - untitled.sublime-workspace
  - vendor/graphql-core/.git
  - vendor/graphql-core/docs
  - vendor/graphql-core/.pytest_cache
  - vendor/graphql-core/scripts
  - vendor/graphql-core/tests
  - vendor/graphql-core/tests_py36
  - vendor/graphene/.git
  - vendor/graphene/docs
  - vendor/graphene/examples
  - vendor/graphene-sqlalchemy
  aws_environment_variables:
    COGNITO_REGION: us-east-1
    COGNITO_USERPOOL_ID: us-east-1_pdrrhWtb9
    SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:TbtjkTxRaamC3ZvGvuEUfngs@sts-dev2-db.cluster-cxxwptxqt1gl.us-east-1.rds.amazonaws.com:3306/sts
  cors: true
  use_precompiled_packages: true
dev2:
  app_function: run.app
  aws_region: us-east-1
  profile_name: default
  project_name: sts
  runtime: python3.7
  s3_bucket: sts-backend
  exclude:
  - .git
  - .gitignore
  - .gitsubmodules
  - .graphqlconfig.yaml
  - .pytest_cache
  - .python-version
  - .pytest_cache
  - local
  - tests
  - scripts
  - venv
  - orka_api.egg-info
  - pip-wheel-metadata
  - README.md
  - schema.graphql
  - tasks.py
  - orka_api/db.db
  - Orka-API-Context-for-Insomnia.yaml
  - untitled.sublime-project
  - untitled.sublime-workspace
  - vendor/graphql-core/.git
  - vendor/graphql-core/docs
  - vendor/graphql-core/.pytest_cache
  - vendor/graphql-core/scripts
  - vendor/graphql-core/tests
  - vendor/graphql-core/tests_py36
  - vendor/graphene/.git
  - vendor/graphene/docs
  - vendor/graphene/examples
  - vendor/graphene-sqlalchemy
  aws_environment_variables:
    COGNITO_REGION: us-east-1
    COGNITO_USERPOOL_ID: us-east-1_pdrrhWtb9
    SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:TbtjkTxRaamC3ZvGvuEUfngs@sts-dev2-db.cluster-cxxwptxqt1gl.us-east-1.rds.amazonaws.com:3306/sts
  cors: true
  use_precompiled_packages: true

